version: "3.9"

networks:
  attack:
    name: attack

services:
  server:
    build: './server'
    working_dir: /scripts
    volumes:
      - './server:/scripts'
    networks: 
      - attack

  attacker:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}
  
  attacker2:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker3:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker4:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker5:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker6:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker7:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker8:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker9:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker10:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker11:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}
  
  attacker12:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker13:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker14:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker15:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker16:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker17:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker18:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker19:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

  attacker20:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}

