version: "3.9"

networks:
  attack:
    name: attack

services:
  server:
    build: './server'
    working_dir: /scripts
    volumes:
      - './server:/scripts'
    networks: 
      - attack

  attacker:
    build: ./attacker
    working_dir: /scripts
    volumes:
      - './attacker:/scripts'
    networks:
      - attack
    environment:
      SCRIPT_PATH: ${SCRIPT_PATH}